package net.juntermanns.mybuttons.ui.main;

import java.util.HashMap;

public class AsiaMap {
    public static HashMap<String, Object[]> asiaMap = new HashMap<>();

    private String afghanistan;
    private String armenia;
    private String australia;
    private String azerbaijan;
    private String bahrain;
    private String bangladesh;
    private String bhutan;
    private String brunei;
    private String cambodia;
    private String china;
    private String cyprus;
    private String georgia;
    private String india;
    private String indonesia;
    private String iran;
    private String iraq;
    private String israel;
    private String japan;
    private String jordan;
    private String kazakhstan;
    private String kuwait;
    private String kyrgyzstan;
    private String laos;
    private String lebanon;
    private String malaysia;
    private String maldives;
    private String mongolia;
    private String myanmar;
    private String nepal;
    private String newzealand;
    private String northkorea;
    private String oman;
    private String pakistan;
    private String palestine;
    private String phillippines;
    private String qatar;
    private String russia;
    private String saudiarabia;
    private String singapore;
    private String southkorea;
    private String srilanka;
    private String syria;
    private String taiwan;
    private String tajikistan;
    private String thailand;
    private String timorleste;
    private String turkey;
    private String turkmenistan;
    private String unitedarabemirates;
    private String uzbekistan;
    private String vietnam;
    private String yemen;

    public AsiaMap() {
        afghanistan = "🇦🇫";
        azerbaijan = "🇦🇿";
        australia = "🇦🇺";
        armenia = "🇦🇲";
        bahrain = "🇧🇭";
        bangladesh = "🇧🇩";
        bhutan = "🇧🇹";
        brunei = "🇧🇳";
        china = "🇨🇳";
        cambodia = "🇰🇭";
        china = "🇨🇳";
        cyprus = "🇨🇾";
        georgia = "🇬🇪";
        india = "🇮🇳";
        indonesia = "🇮🇩";
        iran = "🇮🇷" ;
        iraq = "🇮🇶";
        israel =  "🇮🇱";
        japan = "🇯🇵";
        jordan = "🇯🇴" ;
        kazakhstan =  "🇰🇿";
        kuwait = "🇰🇼";
        kyrgyzstan = "🇰🇬";
        laos = "🇱🇦";
        lebanon = "🇱🇧";
        malaysia = "🇲🇾";
        maldives = "🇲🇻";
        mongolia = "🇲🇳";
        myanmar = "🇲🇲";
        nepal = "🇳🇵";
        newzealand = "🇳🇿";
        northkorea = "🇰🇵" ;
        oman = "🇴🇲";
        pakistan = "🇵🇰";
        palestine = "🇵🇸";
        phillippines = "🇵🇭";
        qatar = "🇶🇦";
        russia = "🇷🇺";
        saudiarabia = "🇸🇦";
        singapore = "🇸🇬";
        southkorea = "🇰🇷";
        srilanka = "🇱🇰";
        syria = "🇸🇾";
        taiwan = "🇹🇼" ;
        tajikistan = "🇹🇯";
        thailand = "🇹🇭";
        timorleste = "🇹🇱";
        turkey = "🇹🇷" ;
        turkmenistan = "🇹🇲" ;
        unitedarabemirates = "🇦🇪";
        uzbekistan = "🇺🇿" ;
        vietnam = "🇻🇳";
        yemen = "🇾🇪";

    }

    public static AsiaMap getAsiaMap(AsiaMap instanz) {

        asiaMap.put("0", new Object[]{instanz.afghanistan, "Afghanistan", "Kabul", 652864, 34940837});
        asiaMap.put("1", new Object[]{instanz.armenia, "Armenien", "Jerewan", 443, 102012});
        asiaMap.put("2",new Object[]{instanz.azerbaijan,"Aserbaidschan","Baku", 86600, 10357175});
        asiaMap.put("3",new Object[]{instanz.bahrain,"Bahrain","Manama", 750, 1493000});
        asiaMap.put("4",new Object[]{instanz.bangladesh,"Bangladesch","Dhaka", 147570, 164800000 });
        asiaMap.put("5",new Object[]{instanz.bhutan,"Bhutan","Thimphu", 38394, 741700});
        asiaMap.put("6",new Object[]{instanz.brunei,"Brunei","Bandar Seri Begawan", 5765, 429000});
        asiaMap.put("7",new Object[]{instanz.cambodia,"Kambodscha","Phnom Penh", 181040, 16005000});
        asiaMap.put("8",new Object[]{instanz.china,"China","Peking", 9596960, 1400050000});
        asiaMap.put("9",new Object[]{instanz.cyprus,"Zypern","Nikosia", 9251, 1179551});
        asiaMap.put("10",new Object[]{instanz.georgia,"Georgien","Tiflis", 69700, 3729635});
        asiaMap.put("11",new Object[]{instanz.india,"Indien","Neu-Delhi", 3287469, 1.368738000});
        asiaMap.put("12",new Object[]{instanz.indonesia,"Indonesien","Jakarta", 1904569, 264160000});   //TODO weitermachen
        asiaMap.put("13",new Object[]{instanz.iran,"Iran","Teheran", 1648195, 81800269});
        asiaMap.put("14",new Object[]{instanz.iraq,"Irak","Bagdad", 343128 , 38654000});
        asiaMap.put("15",new Object[]{instanz.israel,"Israel","Jerusalem", 22380, 9136000});
        asiaMap.put("16",new Object[]{instanz.japan,"Japan","Tokio", 377975, 126860000});
        asiaMap.put("17",new Object[]{instanz.jordan,"Jordanien","Amman", 89342, 10458413});
        asiaMap.put("18",new Object[]{instanz.kazakhstan,"Kasachstan","Nur-Sultan", 2724900, 18632169});
        asiaMap.put("19",new Object[]{instanz.kuwait,"Kuwait","Kuwait-Stadt", 17818, 4132415});
        asiaMap.put("20",new Object[]{instanz.kyrgyzstan,"Kirgisistan","Bischkek", 199900, 6256700});
        asiaMap.put("21",new Object[]{instanz.laos,"Laos","Vientiane", 236800, 7038000});
        asiaMap.put("22",new Object[]{instanz.lebanon,"Libanon","Beirut", 10452, 6100075});
        asiaMap.put("23",new Object[]{instanz.malaysia,"Malaysia","Kuala Lumpur", 330290, 32382300});
        asiaMap.put("24",new Object[]{instanz.maldives,"Malediven","Malé", 298, 409163});
        asiaMap.put("25",new Object[]{instanz.mongolia,"Mongolei","Ulaanbaatar", 1564116, 3103428 });
        asiaMap.put("26",new Object[]{instanz.myanmar,"Myanmar","Naypyidaw", 676578, 53370609});
        asiaMap.put("27",new Object[]{instanz.nepal,"Nepal","Kathmandu",147.181, 28090000});
        asiaMap.put("28",new Object[]{instanz.northkorea,"Nordkorea","Pjöngjang", 120538, 25549604});
        asiaMap.put("29",new Object[]{instanz.oman,"Oman","Maskat", 309500, 4829483});
        asiaMap.put("30",new Object[]{instanz.pakistan,"Pakistan","Islamabad", 796095, 216565000});
        asiaMap.put("31",new Object[]{instanz.palestine,"Palästina","Ramallah", 6020, 4695000});
        asiaMap.put("32",new Object[]{instanz.phillippines,"Phillippinen","Manila", 343448, 106512000});
        asiaMap.put("33",new Object[]{instanz.qatar,"Katar","Doha", 11627, 2700000});
        asiaMap.put("34",new Object[]{instanz.russia,"Russland","Moskau",17075400 , 144526636});
        asiaMap.put("35",new Object[]{instanz.saudiarabia,"Saudi Arabien","Riad", 2149690, 33938709});
        asiaMap.put("36",new Object[]{instanz.singapore,"Singapur","Singapur", 7251, 5703600});
        asiaMap.put("37",new Object[]{instanz.southkorea,"Südkorea","Seoul",100210, 51629512});
        asiaMap.put("38",new Object[]{instanz.srilanka,"Sri Lanka"," Colombo", 65610, 21670000});
        asiaMap.put("39",new Object[]{instanz.syria,"Syrien","Damaskus", 185180, 20960588});
        asiaMap.put("40",new Object[]{instanz.taiwan,"Taiwan","Taipeh", 36179, 23574274});
        asiaMap.put("41",new Object[]{instanz.tajikistan,"Tadschikistan","Duschanbe", 143100, 9100000});
        asiaMap.put("42",new Object[]{instanz.thailand,"Thailand","Bangkok", 513115, 69428524});
        asiaMap.put("43",new Object[]{instanz.timorleste,"Osttimor","Dili", 4.919, 1260000});
        asiaMap.put("44",new Object[]{instanz.turkey,"Türkei","Ankara",783562  , 83154997});
        asiaMap.put("45",new Object[]{instanz.turkmenistan,"Turkmenistan","Aşgabat", 488100, 5942000});
        asiaMap.put("46",new Object[]{instanz.unitedarabemirates,"Vereinigte Arabische Emirate","Abu Dhabi", 83600, 11088});
        asiaMap.put("47",new Object[]{instanz.uzbekistan,"Usbekistan","Taschkent", 448978, 33255539});
        asiaMap.put("48",new Object[]{instanz.vietnam,"Vietnam","Hanoi", 331690 , 95546000});
        asiaMap.put("49",new Object[]{instanz.yemen,"Jemen","Aden", 528076 , 30536729});
        asiaMap.put("50",new Object[]{instanz.australia,"Australien","Canberra"});
        asiaMap.put("51",new Object[]{instanz.newzealand,"Neuseeland","Wellington"});

        return instanz;

}
}
